logging:
    level:
        jooq: trace
        org.blackdread.sqltojava: DEBUG

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
#       url: jdbc:mysql://localhost:3306/?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#       url: jdbc:mysql://localhost:3306/lemongod?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
        url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
        username: root
        password: cw8904
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jooq:
        sql-dialect: mysql


application:
    database-to-export: auth
    ignored-table-names:
        - databasechangelog
        - databasechangeloglock
        - QRTZ_BLOB_TRIGGERS
        - QRTZ_CALENDARS
        - QRTZ_CRON_TRIGGERS
        - QRTZ_FIRED_TRIGGERS
        - QRTZ_JOB_DETAILS
        - QRTZ_LOCKS
        - QRTZ_PAUSED_TRIGGER_GRPS
        - QRTZ_SCHEDULER_STATE
        - QRTZ_SIMPLE_TRIGGERS
        - QRTZ_SIMPROP_TRIGGERS
        - QRTZ_TRIGGERS
        - oauth_access_token
        - oauth_approvals
        - oauth_code
        - oauth_refresh_token
    export:
        path: ./11.0415_goh_auth.jdl
        type: jdl
