-- DROP SCHEMA 

CREATE SCHEMA AUTHORIZATION lmhc_dba;

COMMENT ON SCHEMA IS '시스템 관리 및 공통 테이블용';

 
-- DROP TABLE app_mst;

CREATE TABLE app_mst (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 앱id
	app_nm varchar(50) NOT NULL, -- 앱이름
	app_state varchar(20) NOT NULL, -- 앱제품단계
	app_ver varchar(20) NOT NULL, -- 최신앱버전
	fcm_key varchar(2048) NULL, -- FCM키
	fido_api_key varchar(256) NULL, -- FIDO API키
	multi_enabled bool NOT NULL DEFAULT true, -- 다중단말허용
	nice_site_cd varchar(20) NULL, -- 인증사이트코드
	nice_site_pwd varchar(50) NULL, -- 인증사이트암호
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	CONSTRAINT pk_app_mst PRIMARY KEY (id)
)
TABLESPACE ts_adm
;
COMMENT ON TABLE app_mst IS '앱관리';

-- Column comments

COMMENT ON COLUMN app_mst.id IS '앱id';
COMMENT ON COLUMN app_mst.app_nm IS '앱이름';
COMMENT ON COLUMN app_mst.app_state IS '앱제품단계';
COMMENT ON COLUMN app_mst.app_ver IS '최신앱버전';
COMMENT ON COLUMN app_mst.fcm_key IS 'FCM키';
COMMENT ON COLUMN app_mst.fido_api_key IS 'FIDO API키';
COMMENT ON COLUMN app_mst.multi_enabled IS '다중단말허용';
COMMENT ON COLUMN app_mst.nice_site_cd IS '인증사이트코드';
COMMENT ON COLUMN app_mst.nice_site_pwd IS '인증사이트암호';
COMMENT ON COLUMN app_mst.created_by IS '입력자id';
COMMENT ON COLUMN app_mst.created_on IS '입력일시';
COMMENT ON COLUMN app_mst.updated_by IS '수정자id';
COMMENT ON COLUMN app_mst.updated_on IS '수정일시';


-- banner_info definition

-- Drop table

-- DROP TABLE banner_info;

CREATE TABLE banner_info (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 배너id
	banner_nm varchar(50) NOT NULL, -- 배너명
	image_url varchar(256) NOT NULL, -- 이미지경로
	link_url varchar(256) NULL, -- 링크url
	started_on timestamp NOT NULL, -- 게시시작일시
	ended_on timestamp NOT NULL DEFAULT '2099-12-31 00:00:00'::timestamp without time zone, -- 게시종료일시
	enabled bool NOT NULL DEFAULT false, -- 노출여부
	file_nm varchar(256) NULL, -- 파일이름
	link_type varchar(20) NOT NULL, -- 링크방식
	hit_cnt int4 NOT NULL DEFAULT 0, -- 히트수
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	CONSTRAINT pk_banner_info PRIMARY KEY (id)
);
COMMENT ON TABLE banner_info IS '배너관리';

-- Column comments

COMMENT ON COLUMN banner_info.id IS '배너id';
COMMENT ON COLUMN banner_info.banner_nm IS '배너명';
COMMENT ON COLUMN banner_info.image_url IS '이미지경로';
COMMENT ON COLUMN banner_info.link_url IS '링크url';
COMMENT ON COLUMN banner_info.started_on IS '게시시작일시';
COMMENT ON COLUMN banner_info.ended_on IS '게시종료일시';
COMMENT ON COLUMN banner_info.enabled IS '노출여부';
COMMENT ON COLUMN banner_info.file_nm IS '파일이름';
COMMENT ON COLUMN banner_info.link_type IS '링크방식';
COMMENT ON COLUMN banner_info.hit_cnt IS '히트수';
COMMENT ON COLUMN banner_info.created_by IS '입력자id';
COMMENT ON COLUMN banner_info.created_on IS '입력일시';
COMMENT ON COLUMN banner_info.updated_by IS '수정자id';
COMMENT ON COLUMN banner_info.updated_on IS '수정일시';


-- board definition

-- Drop table

-- DROP TABLE board;

CREATE TABLE board (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 게시판id
	service_cd varchar(30) NOT NULL, -- 레몬서비스코드
	board_nm varchar(30) NOT NULL, -- 게시판명
	board_desc varchar(1000) NOT NULL, -- 게시판설명
	board_type varchar(20) NOT NULL, -- 게시판종류
	comp_type varchar(20) NOT NULL, -- 기관구분
	comp_cd varchar(20) NOT NULL, -- 기관id
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	CONSTRAINT pk_board PRIMARY KEY (id)
)
TABLESPACE ts_adm
;
COMMENT ON TABLE board IS '게시판';

-- Column comments

COMMENT ON COLUMN board.id IS '게시판id';
COMMENT ON COLUMN board.service_cd IS '레몬서비스코드';
COMMENT ON COLUMN board.board_nm IS '게시판명';
COMMENT ON COLUMN board.board_desc IS '게시판설명';
COMMENT ON COLUMN board.board_type IS '게시판종류';
COMMENT ON COLUMN board.comp_type IS '기관구분';
COMMENT ON COLUMN board.comp_cd IS '기관id';
COMMENT ON COLUMN board.created_by IS '입력자id';
COMMENT ON COLUMN board.created_on IS '입력일시';
COMMENT ON COLUMN board.updated_by IS '수정자id';
COMMENT ON COLUMN board.updated_on IS '수정일시';


-- code_mst definition

-- Drop table

-- DROP TABLE code_mst;

CREATE TABLE code_mst (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 코드id
	code_cls varchar(20) NOT NULL, -- 분류코드
	code_type varchar(20) NOT NULL, -- 유형
	code varchar(20) NOT NULL, -- 코드
	code_nm varchar(128) NOT NULL, -- 코드명
	code_nm_eng varchar(128) NULL, -- 코드영문명
	code_desc varchar(1000) NULL, -- 코드설명
	disp_ord varchar(10) NOT NULL, -- 표시순서
	ref_val varchar(20) NULL, -- 참조값
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	CONSTRAINT pk_code_mst PRIMARY KEY (id),
	CONSTRAINT uk_code_mst UNIQUE (code_cls, code)
)
TABLESPACE ts_adm
;
CREATE INDEX ix_code_mst1 ON code_mst USING btree (code_nm);
COMMENT ON TABLE code_mst IS '코드관리';

-- Column comments

COMMENT ON COLUMN code_mst.id IS '코드id';
COMMENT ON COLUMN code_mst.code_cls IS '분류코드';
COMMENT ON COLUMN code_mst.code_type IS '유형';
COMMENT ON COLUMN code_mst.code IS '코드';
COMMENT ON COLUMN code_mst.code_nm IS '코드명';
COMMENT ON COLUMN code_mst.code_nm_eng IS '코드영문명';
COMMENT ON COLUMN code_mst.code_desc IS '코드설명';
COMMENT ON COLUMN code_mst.disp_ord IS '표시순서';
COMMENT ON COLUMN code_mst.ref_val IS '참조값';
COMMENT ON COLUMN code_mst.created_by IS '입력자id';
COMMENT ON COLUMN code_mst.created_on IS '입력일시';
COMMENT ON COLUMN code_mst.updated_by IS '수정자id';
COMMENT ON COLUMN code_mst.updated_on IS '수정일시';


-- event_mst definition

-- Drop table

-- DROP TABLE event_mst;

CREATE TABLE event_mst (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	event_type varchar(10) NOT NULL,
	event_nm varchar(50) NOT NULL,
	service_cd varchar(30) NOT NULL,
	started_on timestamp NOT NULL,
	ended_on timestamp NOT NULL,
	valid_days int4 NOT NULL,
	event_desc varchar(1000) NOT NULL,
	save_type varchar(10) NOT NULL,
	save_val int4 NOT NULL,
	event_memo varchar(1000) NOT NULL,
	created_by int8 NOT NULL,
	created_on timestamp NOT NULL,
	updated_by int8 NULL,
	updated_on timestamp NULL,
	CONSTRAINT pk_event_mst PRIMARY KEY (id)
)
TABLESPACE ts_adm
;


-- group_def definition

-- Drop table

-- DROP TABLE group_def;

CREATE TABLE group_def (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 그룹id
	group_nm varchar(50) NOT NULL, -- 그룹명
	group_nm_nls varchar(100) NULL, -- 그룹명다국어
	disp_ord varchar(10) NOT NULL, -- 표시순서
	group_desc varchar(200) NOT NULL, -- 설명
	service_url varchar(256) NULL, -- 서비스url
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	CONSTRAINT pk_group_def PRIMARY KEY (id)
)
TABLESPACE ts_adm
;
COMMENT ON TABLE group_def IS '그룹정의';

-- Column comments

COMMENT ON COLUMN group_def.id IS '그룹id';
COMMENT ON COLUMN group_def.group_nm IS '그룹명';
COMMENT ON COLUMN group_def.group_nm_nls IS '그룹명다국어';
COMMENT ON COLUMN group_def.disp_ord IS '표시순서';
COMMENT ON COLUMN group_def.group_desc IS '설명';
COMMENT ON COLUMN group_def.service_url IS '서비스url';
COMMENT ON COLUMN group_def.created_by IS '입력자id';
COMMENT ON COLUMN group_def.created_on IS '입력일시';
COMMENT ON COLUMN group_def.updated_by IS '수정자id';
COMMENT ON COLUMN group_def.updated_on IS '수정일시';


-- hospital_mst definition

-- Drop table

-- DROP TABLE hospital_mst;

CREATE TABLE hospital_mst (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 병원id
	enabled bool NOT NULL DEFAULT true, -- 사용여부
	hospital_cd varchar(20) NULL, -- 요양기관코드
	hospital_nm varchar(50) NOT NULL, -- 병원명
	post_no varchar(6) NULL, -- 우편번호
	road_addr varchar(120) NULL, -- 도로명주소
	lot_addr varchar(120) NULL, -- 지번주소
	phone_no varchar(30) NULL, -- 대표전화
	hospital_nm_nls varchar(100) NULL, -- 다국어병원명
	addr_nls varchar(150) NULL, -- 다국어주소
	domain_url varchar(256) NULL, -- QAB도메인
	api_url varchar(256) NULL, -- API주소
	api_open_date date NULL, -- 입점오픈일
	open_date date NULL, -- 개원일자
	home_url varchar(256) NULL, -- 홈페이지URL
	intro_content text NULL, -- 병원소개내용
	logo_url varchar(256) NULL, -- 로고URL
	campain_txt varchar(1000) NULL, -- 캠페인문구
	location_txt varchar(1000) NULL, -- 오시는길
	parking_txt varchar(1000) NULL, -- 주차안내
	emergency_txt varchar(1000) NULL, -- 응급실안내
	open_hours_txt varchar(1000) NULL, -- 운영시간안내
	holiday_txt varchar(1000) NULL, -- 휴일안내
	treat_txt varchar(1000) NULL, -- 진료과목
	hash_tag varchar(256) NULL, -- 해시태그
	latitude varchar(18) NULL, -- 위도
	longitude varchar(18) NULL, -- 경도
	star_score numeric(9,3) NULL, -- 평점
	review_cnt int4 NULL, -- 리뷰개수
	doctor_cnt int4 NULL, -- 전체의사수
	gdoctor_cnt int4 NULL, -- 일반의수
	sdoctor_cnt int4 NULL, -- 전문의수
	idoctor_cnt int4 NULL, -- 인턴수
	rdoctor_cnt int4 NULL, -- 레지던트수
	hospital_nm_short varchar(50) NULL, -- 병원명약어
	hospital_type varchar(20) NULL, -- 병원종별코드
	metro_cd varchar(20) NULL, -- 시도코드
	city_cd varchar(20) NULL, -- 시군구코드
	bed_cnt int4 NULL, -- 병상수
	daily_visit_cnt int4 NULL, -- 일내원환자수
	ykiho varchar(300) NULL, -- 의료기관식별값
	barcode_spec varchar(20) NULL, -- 바코드규격
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	day_er_enabled bool NULL, -- 주간응급여부
	night_er_enabled bool NULL, -- 야간응급여부
	CONSTRAINT pk_hospital_mst PRIMARY KEY (id)
)
TABLESPACE ts_adm
;
CREATE INDEX ix_hospital_mst1 ON hospital_mst USING btree (hospital_nm);
CREATE INDEX ix_hospital_mst2 ON hospital_mst USING btree (ykiho);
CREATE INDEX ix_hospital_mst3 ON hospital_mst USING btree (latitude, longitude);
CREATE INDEX ix_hospital_mst4 ON hospital_mst USING btree (hash_tag);
CREATE INDEX ix_hospital_mst5 ON hospital_mst USING btree (hospital_cd);
COMMENT ON TABLE hospital_mst IS '병원정보';

-- Column comments

COMMENT ON COLUMN hospital_mst.id IS '병원id';
COMMENT ON COLUMN hospital_mst.enabled IS '사용여부';
COMMENT ON COLUMN hospital_mst.hospital_cd IS '요양기관코드';
COMMENT ON COLUMN hospital_mst.hospital_nm IS '병원명';
COMMENT ON COLUMN hospital_mst.post_no IS '우편번호';
COMMENT ON COLUMN hospital_mst.road_addr IS '도로명주소';
COMMENT ON COLUMN hospital_mst.lot_addr IS '지번주소';
COMMENT ON COLUMN hospital_mst.phone_no IS '대표전화';
COMMENT ON COLUMN hospital_mst.hospital_nm_nls IS '다국어병원명';
COMMENT ON COLUMN hospital_mst.addr_nls IS '다국어주소';
COMMENT ON COLUMN hospital_mst.domain_url IS 'QAB도메인';
COMMENT ON COLUMN hospital_mst.api_url IS 'API주소';
COMMENT ON COLUMN hospital_mst.api_open_date IS '입점오픈일';
COMMENT ON COLUMN hospital_mst.open_date IS '개원일자';
COMMENT ON COLUMN hospital_mst.home_url IS '홈페이지URL';
COMMENT ON COLUMN hospital_mst.intro_content IS '병원소개내용';
COMMENT ON COLUMN hospital_mst.logo_url IS '로고URL';
COMMENT ON COLUMN hospital_mst.campain_txt IS '캠페인문구';
COMMENT ON COLUMN hospital_mst.location_txt IS '오시는길';
COMMENT ON COLUMN hospital_mst.parking_txt IS '주차안내';
COMMENT ON COLUMN hospital_mst.emergency_txt IS '응급실안내';
COMMENT ON COLUMN hospital_mst.open_hours_txt IS '운영시간안내';
COMMENT ON COLUMN hospital_mst.holiday_txt IS '휴일안내';
COMMENT ON COLUMN hospital_mst.treat_txt IS '진료과목';
COMMENT ON COLUMN hospital_mst.hash_tag IS '해시태그';
COMMENT ON COLUMN hospital_mst.latitude IS '위도';
COMMENT ON COLUMN hospital_mst.longitude IS '경도';
COMMENT ON COLUMN hospital_mst.star_score IS '평점';
COMMENT ON COLUMN hospital_mst.review_cnt IS '리뷰개수';
COMMENT ON COLUMN hospital_mst.doctor_cnt IS '전체의사수';
COMMENT ON COLUMN hospital_mst.gdoctor_cnt IS '일반의수';
COMMENT ON COLUMN hospital_mst.sdoctor_cnt IS '전문의수';
COMMENT ON COLUMN hospital_mst.idoctor_cnt IS '인턴수';
COMMENT ON COLUMN hospital_mst.rdoctor_cnt IS '레지던트수';
COMMENT ON COLUMN hospital_mst.hospital_nm_short IS '병원명약어';
COMMENT ON COLUMN hospital_mst.hospital_type IS '병원종별코드';
COMMENT ON COLUMN hospital_mst.metro_cd IS '시도코드';
COMMENT ON COLUMN hospital_mst.city_cd IS '시군구코드';
COMMENT ON COLUMN hospital_mst.bed_cnt IS '병상수';
COMMENT ON COLUMN hospital_mst.daily_visit_cnt IS '일내원환자수';
COMMENT ON COLUMN hospital_mst.ykiho IS '의료기관식별값';
COMMENT ON COLUMN hospital_mst.barcode_spec IS '바코드규격';
COMMENT ON COLUMN hospital_mst.created_by IS '입력자id';
COMMENT ON COLUMN hospital_mst.created_on IS '입력일시';
COMMENT ON COLUMN hospital_mst.updated_by IS '수정자id';
COMMENT ON COLUMN hospital_mst.updated_on IS '수정일시';
COMMENT ON COLUMN hospital_mst.day_er_enabled IS '주간응급여부';
COMMENT ON COLUMN hospital_mst.night_er_enabled IS '야간응급여부';


-- i18n_msg definition

-- Drop table

-- DROP TABLE i18n_msg;

CREATE TABLE i18n_msg (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 메세지id
	lang_cd varchar(100) NOT NULL, -- 언어코드
	msg_cd varchar(100) NOT NULL, -- 메시지코드
	msg_content varchar(1000) NOT NULL, -- 메시지명
	popup_type varchar(10) NULL, -- 팝업종류
	popup_title varchar(20) NULL, -- 팝업타이틀
	ok_button_nm varchar(20) NULL, -- 확인버튼명
	cancel_button_nm varchar(20) NULL, -- 취소버튼명
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	CONSTRAINT pk_i18n_msg PRIMARY KEY (id),
	CONSTRAINT uk_i18n_msg UNIQUE (lang_cd, msg_cd)
)
TABLESPACE ts_adm
;
CREATE INDEX ix_i18n_msg1 ON i18n_msg USING btree (msg_content);
COMMENT ON TABLE i18n_msg IS '다국어정의';

-- Column comments

COMMENT ON COLUMN i18n_msg.id IS '메세지id';
COMMENT ON COLUMN i18n_msg.lang_cd IS '언어코드';
COMMENT ON COLUMN i18n_msg.msg_cd IS '메시지코드';
COMMENT ON COLUMN i18n_msg.msg_content IS '메시지명';
COMMENT ON COLUMN i18n_msg.popup_type IS '팝업종류';
COMMENT ON COLUMN i18n_msg.popup_title IS '팝업타이틀';
COMMENT ON COLUMN i18n_msg.ok_button_nm IS '확인버튼명';
COMMENT ON COLUMN i18n_msg.cancel_button_nm IS '취소버튼명';
COMMENT ON COLUMN i18n_msg.created_by IS '입력자id';
COMMENT ON COLUMN i18n_msg.created_on IS '입력일시';
COMMENT ON COLUMN i18n_msg.updated_by IS '수정자id';
COMMENT ON COLUMN i18n_msg.updated_on IS '수정일시';


-- lemon_config definition

-- Drop table

-- DROP TABLE lemon_config;

CREATE TABLE lemon_config (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 정책id
	policy_cd varchar(20) NOT NULL, -- 정책종류
	policy_nm varchar(50) NOT NULL, -- 정책명
	service_cd varchar(30) NOT NULL, -- 레몬서비스코드
	started_on timestamp NOT NULL, -- 시작일시
	ended_on timestamp NOT NULL, -- 종료일시
	policy_desc varchar(1000) NOT NULL, -- 정책설명
	max_val numeric(9,3) NOT NULL, -- 상한값
	min_val numeric(9,3) NOT NULL, -- 하한값
	return_msg varchar(200) NULL, -- 리턴메시지
	CONSTRAINT pk_lemon_config PRIMARY KEY (id)
)
TABLESPACE ts_adm
;
COMMENT ON TABLE lemon_config IS '서비스정책관리';

-- Column comments

COMMENT ON COLUMN lemon_config.id IS '정책id';
COMMENT ON COLUMN lemon_config.policy_cd IS '정책종류';
COMMENT ON COLUMN lemon_config.policy_nm IS '정책명';
COMMENT ON COLUMN lemon_config.service_cd IS '레몬서비스코드';
COMMENT ON COLUMN lemon_config.started_on IS '시작일시';
COMMENT ON COLUMN lemon_config.ended_on IS '종료일시';
COMMENT ON COLUMN lemon_config.policy_desc IS '정책설명';
COMMENT ON COLUMN lemon_config.max_val IS '상한값';
COMMENT ON COLUMN lemon_config.min_val IS '하한값';
COMMENT ON COLUMN lemon_config.return_msg IS '리턴메시지';


-- menu_def definition

-- Drop table

-- DROP TABLE menu_def;

CREATE TABLE menu_def (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 메뉴id
	service_cd varchar(30) NOT NULL, -- 레몬서비스코드
	menu_nm varchar(50) NOT NULL, -- 메뉴명
	menu_nm_nls varchar(100) NULL, -- 메뉴명다국어
	menu_desc varchar(200) NULL, -- 메뉴설명
	img_url varchar(256) NULL, -- 이미지url
	service_url varchar(256) NULL, -- 서비스url
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	CONSTRAINT pk_menu_def PRIMARY KEY (id)
)
TABLESPACE ts_adm
;
COMMENT ON TABLE menu_def IS '메뉴정의';

-- Column comments

COMMENT ON COLUMN menu_def.id IS '메뉴id';
COMMENT ON COLUMN menu_def.service_cd IS '레몬서비스코드';
COMMENT ON COLUMN menu_def.menu_nm IS '메뉴명';
COMMENT ON COLUMN menu_def.menu_nm_nls IS '메뉴명다국어';
COMMENT ON COLUMN menu_def.menu_desc IS '메뉴설명';
COMMENT ON COLUMN menu_def.img_url IS '이미지url';
COMMENT ON COLUMN menu_def.service_url IS '서비스url';
COMMENT ON COLUMN menu_def.created_by IS '입력자id';
COMMENT ON COLUMN menu_def.created_on IS '입력일시';
COMMENT ON COLUMN menu_def.updated_by IS '수정자id';
COMMENT ON COLUMN menu_def.updated_on IS '수정일시';


-- pharmacy_info definition

-- Drop table

-- DROP TABLE pharmacy_info;

CREATE TABLE pharmacy_info (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 약국id
	enabled bool NOT NULL DEFAULT true, -- 사용여부
	ykiho varchar(300) NULL, -- 공공식별값
	pharmacy_nm varchar(30) NOT NULL, -- 약국명
	post_no varchar(6) NULL, -- 우편번호
	road_addr varchar(120) NULL, -- 도로명주소
	lot_addr varchar(120) NULL, -- 지번주소
	phone_no varchar(20) NULL, -- 대표전화
	op_hours_txt varchar(500) NULL, -- 운영시간안내
	hash_tag varchar(256) NULL, -- 해시태그
	latitude varchar(18) NULL, -- 위도
	longitude varchar(18) NULL, -- 경도
	star_score numeric(9,3) NULL, -- 평점
	review_cnt int4 NULL, -- 리뷰개수
	created_on timestamp NOT NULL, -- 입력일시
	updated_on timestamp NULL, -- 수정일자
	CONSTRAINT pk_pharmacy_info PRIMARY KEY (id)
)
TABLESPACE ts_adm
;
CREATE INDEX ix_pharmacy_info1 ON pharmacy_info USING btree (pharmacy_nm);
CREATE INDEX ix_pharmacy_info2 ON pharmacy_info USING btree (latitude, longitude);
CREATE INDEX ix_pharmacy_info3 ON pharmacy_info USING btree (hash_tag);
CREATE INDEX ix_pharmacy_info4 ON pharmacy_info USING btree (ykiho);
COMMENT ON TABLE pharmacy_info IS '약국정보';

-- Column comments

COMMENT ON COLUMN pharmacy_info.id IS '약국id';
COMMENT ON COLUMN pharmacy_info.enabled IS '사용여부';
COMMENT ON COLUMN pharmacy_info.ykiho IS '공공식별값';
COMMENT ON COLUMN pharmacy_info.pharmacy_nm IS '약국명';
COMMENT ON COLUMN pharmacy_info.post_no IS '우편번호';
COMMENT ON COLUMN pharmacy_info.road_addr IS '도로명주소';
COMMENT ON COLUMN pharmacy_info.lot_addr IS '지번주소';
COMMENT ON COLUMN pharmacy_info.phone_no IS '대표전화';
COMMENT ON COLUMN pharmacy_info.op_hours_txt IS '운영시간안내';
COMMENT ON COLUMN pharmacy_info.hash_tag IS '해시태그';
COMMENT ON COLUMN pharmacy_info.latitude IS '위도';
COMMENT ON COLUMN pharmacy_info.longitude IS '경도';
COMMENT ON COLUMN pharmacy_info.star_score IS '평점';
COMMENT ON COLUMN pharmacy_info.review_cnt IS '리뷰개수';
COMMENT ON COLUMN pharmacy_info.created_on IS '입력일시';
COMMENT ON COLUMN pharmacy_info.updated_on IS '수정일자';


-- post_likes definition

-- Drop table

-- DROP TABLE post_likes;

CREATE TABLE post_likes (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 추천id
	post_id int8 NOT NULL, -- 게시물id
	like_type varchar(20) NOT NULL, -- 추천종류
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	CONSTRAINT pk_post_likes PRIMARY KEY (id)
)
TABLESPACE ts_adm
;
CREATE INDEX ix_post_likes1 ON post_likes USING btree (post_id);
CREATE INDEX ix_post_likes2 ON post_likes USING btree (like_type);
COMMENT ON TABLE post_likes IS '게시물추천';

-- Column comments

COMMENT ON COLUMN post_likes.id IS '추천id';
COMMENT ON COLUMN post_likes.post_id IS '게시물id';
COMMENT ON COLUMN post_likes.like_type IS '추천종류';
COMMENT ON COLUMN post_likes.created_by IS '입력자id';
COMMENT ON COLUMN post_likes.created_on IS '입력일시';


-- post_read definition

-- Drop table

-- DROP TABLE post_read;

CREATE TABLE post_read (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 읽음id
	post_id int8 NOT NULL, -- 게시물id
	read_on timestamp NOT NULL, -- 읽음일시
	user_id int8 NULL, -- 사용자id
	unknown_key varchar(256) NULL, -- 비회원식별값
	CONSTRAINT pk_post_read PRIMARY KEY (id)
)
TABLESPACE ts_adm
;
CREATE INDEX ix_post_read1 ON post_read USING btree (post_id);
CREATE INDEX ix_post_read2 ON post_read USING btree (user_id);
CREATE INDEX ix_post_read3 ON post_read USING btree (unknown_key);
COMMENT ON TABLE post_read IS '게시물읽음관리';

-- Column comments

COMMENT ON COLUMN post_read.id IS '읽음id';
COMMENT ON COLUMN post_read.post_id IS '게시물id';
COMMENT ON COLUMN post_read.read_on IS '읽음일시';
COMMENT ON COLUMN post_read.user_id IS '사용자id';
COMMENT ON COLUMN post_read.unknown_key IS '비회원식별값';


-- role_def definition

-- Drop table

-- DROP TABLE role_def;

CREATE TABLE role_def (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 역할id
	role_nm varchar(50) NOT NULL, -- 역할명
	role_desc varchar(1000) NULL, -- 설명
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	CONSTRAINT pk_role_def PRIMARY KEY (id),
	CONSTRAINT uk_role_def UNIQUE (role_nm)
)
TABLESPACE ts_adm
;
COMMENT ON TABLE role_def IS '역할정의';

-- Column comments

COMMENT ON COLUMN role_def.id IS '역할id';
COMMENT ON COLUMN role_def.role_nm IS '역할명';
COMMENT ON COLUMN role_def.role_desc IS '설명';
COMMENT ON COLUMN role_def.created_by IS '입력자id';
COMMENT ON COLUMN role_def.created_on IS '입력일시';


-- search_hst definition

-- Drop table

-- DROP TABLE search_hst;

CREATE TABLE search_hst (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 검색어id
	search_keyword varchar(50) NOT NULL, -- 검색어
	unknown_key varchar(256) NULL DEFAULT '0'::character varying, -- 비회원식별값
	user_id int8 NULL, -- 사용자id
	searched_on timestamp NOT NULL, -- 검색일시
	CONSTRAINT pk_search_hst PRIMARY KEY (id)
);
CREATE INDEX ix_search_hst1 ON search_hst USING btree (search_keyword);
CREATE INDEX ix_search_hst2 ON search_hst USING btree (searched_on);
CREATE INDEX ix_search_hst3 ON search_hst USING btree (user_id, unknown_key);
COMMENT ON TABLE search_hst IS '검색이력';

-- Column comments

COMMENT ON COLUMN search_hst.id IS '검색어id';
COMMENT ON COLUMN search_hst.search_keyword IS '검색어';
COMMENT ON COLUMN search_hst.unknown_key IS '비회원식별값';
COMMENT ON COLUMN search_hst.user_id IS '사용자id';
COMMENT ON COLUMN search_hst.searched_on IS '검색일시';


-- supplier_mst definition

-- Drop table

-- DROP TABLE supplier_mst;

CREATE TABLE supplier_mst (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 공급사id
	supplier_type varchar(20) NOT NULL, -- 공급사유형
	enabled bool NOT NULL DEFAULT true, -- 사용여부
	supplier_cd varchar(20) NULL, -- 공급사관리코드
	supplier_nm varchar(50) NOT NULL, -- 공급사명
	rep_nm varchar(50) NOT NULL, -- 대표자명
	biz_no varchar(10) NOT NULL, -- 사업자번호
	phone_no varchar(30) NOT NULL, -- 대표전화번호
	post_no varchar(5) NULL, -- 우편번호
	addr1 varchar(128) NULL, -- 사업장도로명주소
	addr2 varchar(128) NULL, -- 사업장상세주소
	calculate_type varchar(20) NULL, -- 정산방법
	memo varchar(1000) NULL, -- 관리메모
	pay_type varchar(20) NULL, -- 결제수단정책
	refund_enabled bool NOT NULL DEFAULT true, -- 환불허용여부
	cancel_enabled bool NOT NULL DEFAULT true, -- 취소허용여부
	mileage_type varchar(20) NULL, -- 마일리지정책
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	CONSTRAINT pk_supplier_mst PRIMARY KEY (id)
)
TABLESPACE ts_adm
;
COMMENT ON TABLE supplier_mst IS '서비스공급사';

-- Column comments

COMMENT ON COLUMN supplier_mst.id IS '공급사id';
COMMENT ON COLUMN supplier_mst.supplier_type IS '공급사유형';
COMMENT ON COLUMN supplier_mst.enabled IS '사용여부';
COMMENT ON COLUMN supplier_mst.supplier_cd IS '공급사관리코드';
COMMENT ON COLUMN supplier_mst.supplier_nm IS '공급사명';
COMMENT ON COLUMN supplier_mst.rep_nm IS '대표자명';
COMMENT ON COLUMN supplier_mst.biz_no IS '사업자번호';
COMMENT ON COLUMN supplier_mst.phone_no IS '대표전화번호';
COMMENT ON COLUMN supplier_mst.post_no IS '우편번호';
COMMENT ON COLUMN supplier_mst.addr1 IS '사업장도로명주소';
COMMENT ON COLUMN supplier_mst.addr2 IS '사업장상세주소';
COMMENT ON COLUMN supplier_mst.calculate_type IS '정산방법';
COMMENT ON COLUMN supplier_mst.memo IS '관리메모';
COMMENT ON COLUMN supplier_mst.pay_type IS '결제수단정책';
COMMENT ON COLUMN supplier_mst.refund_enabled IS '환불허용여부';
COMMENT ON COLUMN supplier_mst.cancel_enabled IS '취소허용여부';
COMMENT ON COLUMN supplier_mst.mileage_type IS '마일리지정책';
COMMENT ON COLUMN supplier_mst.created_by IS '입력자id';
COMMENT ON COLUMN supplier_mst.created_on IS '입력일시';
COMMENT ON COLUMN supplier_mst.updated_by IS '수정자id';
COMMENT ON COLUMN supplier_mst.updated_on IS '수정일시';


-- ui_control_def definition

-- Drop table

-- DROP TABLE ui_control_def;

CREATE TABLE ui_control_def (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 설정id
	service_cd varchar(30) NOT NULL, -- 레몬서비스코드
	comp_type varchar(20) NOT NULL, -- 기관구분
	comp_cd varchar(20) NOT NULL, -- 기관코드
	ctrl_key varchar(20) NOT NULL, -- 화면제어코드
	ctrl_val varchar(50) NOT NULL, -- 화면제어값
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	CONSTRAINT pk_ui_control_def PRIMARY KEY (id),
	CONSTRAINT uk_ui_control_def UNIQUE (service_cd, comp_type, comp_cd, ctrl_key)
)
TABLESPACE ts_adm
;
COMMENT ON TABLE ui_control_def IS '화면제어설정';

-- Column comments

COMMENT ON COLUMN ui_control_def.id IS '설정id';
COMMENT ON COLUMN ui_control_def.service_cd IS '레몬서비스코드';
COMMENT ON COLUMN ui_control_def.comp_type IS '기관구분';
COMMENT ON COLUMN ui_control_def.comp_cd IS '기관코드';
COMMENT ON COLUMN ui_control_def.ctrl_key IS '화면제어코드';
COMMENT ON COLUMN ui_control_def.ctrl_val IS '화면제어값';
COMMENT ON COLUMN ui_control_def.created_by IS '입력자id';
COMMENT ON COLUMN ui_control_def.created_on IS '입력일시';
COMMENT ON COLUMN ui_control_def.updated_by IS '수정자id';
COMMENT ON COLUMN ui_control_def.updated_on IS '수정일시';


-- app_platform definition

-- Drop table

-- DROP TABLE app_platform;

CREATE TABLE app_platform (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 앱플랫폼id
	app_id int8 NOT NULL, -- 앱id
	platform_type varchar(20) NOT NULL, -- 플랫폼타입
	pkg_nm varchar(100) NOT NULL, -- 패키지명
	deploy_type varchar(20) NOT NULL, -- 배포타입
	hash_key varchar(2048) NULL, -- 해시값
	store_url varchar(256) NULL, -- 스토어url
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	ios_processed bool NULL, -- iOS심사상태
	CONSTRAINT pk_app_platform PRIMARY KEY (id),
	CONSTRAINT uk_app_platform UNIQUE (platform_type, pkg_nm),
	CONSTRAINT fk_app_platform_app_mst FOREIGN KEY (app_id) REFERENCES app_mst(id)
)
TABLESPACE ts_adm
;
CREATE INDEX ix_app_platform1 ON app_platform USING btree (app_id);
COMMENT ON TABLE app_platform IS '앱플랫폼관리';

-- Column comments

COMMENT ON COLUMN app_platform.id IS '앱플랫폼id';
COMMENT ON COLUMN app_platform.app_id IS '앱id';
COMMENT ON COLUMN app_platform.platform_type IS '플랫폼타입';
COMMENT ON COLUMN app_platform.pkg_nm IS '패키지명';
COMMENT ON COLUMN app_platform.deploy_type IS '배포타입';
COMMENT ON COLUMN app_platform.hash_key IS '해시값';
COMMENT ON COLUMN app_platform.store_url IS '스토어url';
COMMENT ON COLUMN app_platform.created_by IS '입력자id';
COMMENT ON COLUMN app_platform.created_on IS '입력일시';
COMMENT ON COLUMN app_platform.updated_by IS '수정자id';
COMMENT ON COLUMN app_platform.updated_on IS '수정일시';
COMMENT ON COLUMN app_platform.ios_processed IS 'iOS심사상태';


-- app_version definition

-- Drop table

-- DROP TABLE app_version;

CREATE TABLE app_version (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 앱버전id
	app_platform_id int8 NOT NULL, -- 앱플랫폼id
	version_cd varchar(20) NOT NULL, -- 버전코드
	release_note text NOT NULL, -- 릴리즈노트
	released_on timestamp NOT NULL, -- 릴리즈일자
	required bool NOT NULL DEFAULT false, -- 필수여부
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	CONSTRAINT pk_app_version PRIMARY KEY (id),
	CONSTRAINT uk_app_version UNIQUE (app_platform_id, version_cd),
	CONSTRAINT fk_app_version_app_platform FOREIGN KEY (app_platform_id) REFERENCES app_platform(id)
)
TABLESPACE ts_adm
;
CREATE INDEX ix_app_version1 ON app_version USING btree (app_platform_id);
CREATE INDEX ix_app_version2 ON app_version USING btree (app_platform_id, released_on DESC);
COMMENT ON TABLE app_version IS '앱버전관리';

-- Column comments

COMMENT ON COLUMN app_version.id IS '앱버전id';
COMMENT ON COLUMN app_version.app_platform_id IS '앱플랫폼id';
COMMENT ON COLUMN app_version.version_cd IS '버전코드';
COMMENT ON COLUMN app_version.release_note IS '릴리즈노트';
COMMENT ON COLUMN app_version.released_on IS '릴리즈일자';
COMMENT ON COLUMN app_version.required IS '필수여부';
COMMENT ON COLUMN app_version.created_by IS '입력자id';
COMMENT ON COLUMN app_version.created_on IS '입력일시';
COMMENT ON COLUMN app_version.updated_by IS '수정자id';
COMMENT ON COLUMN app_version.updated_on IS '수정일시';


-- good_doctors definition

-- Drop table

-- DROP TABLE good_doctors;

CREATE TABLE good_doctors (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- id
	eval_ym varchar(6) NOT NULL, -- 평가년월
	hospital_id int8 NULL, -- 병원id
	hospital_nm varchar(30) NOT NULL, -- 병원명
	dept_nm varchar(50) NOT NULL, -- 진료과명
	open_enabled bool NOT NULL, -- 공개여부
	treat_nm varchar(256) NULL, -- 진료과목명
	doctor_nm varchar(30) NULL, -- 의사명
	doctor_txt varchar(500) NULL, -- 의사소개
	image_url varchar(256) NULL, -- 프로필사진url
	like_cnt int4 NOT NULL, -- 추천수
	est_point numeric(9,3) NOT NULL, -- 평점
	created_on timestamp NOT NULL, -- 입력일시
	CONSTRAINT pk_good_doctors PRIMARY KEY (id),
	CONSTRAINT fk_good_doctors_hospital_mst FOREIGN KEY (hospital_id) REFERENCES hospital_mst(id)
)
TABLESPACE ts_adm
;
CREATE INDEX ix_good_doctors1 ON good_doctors USING btree (eval_ym, hospital_nm, dept_nm, doctor_nm);
COMMENT ON TABLE good_doctors IS '이달의의료인';

-- Column comments

COMMENT ON COLUMN good_doctors.id IS 'id';
COMMENT ON COLUMN good_doctors.eval_ym IS '평가년월';
COMMENT ON COLUMN good_doctors.hospital_id IS '병원id';
COMMENT ON COLUMN good_doctors.hospital_nm IS '병원명';
COMMENT ON COLUMN good_doctors.dept_nm IS '진료과명';
COMMENT ON COLUMN good_doctors.open_enabled IS '공개여부';
COMMENT ON COLUMN good_doctors.treat_nm IS '진료과목명';
COMMENT ON COLUMN good_doctors.doctor_nm IS '의사명';
COMMENT ON COLUMN good_doctors.doctor_txt IS '의사소개';
COMMENT ON COLUMN good_doctors.image_url IS '프로필사진url';
COMMENT ON COLUMN good_doctors.like_cnt IS '추천수';
COMMENT ON COLUMN good_doctors.est_point IS '평점';
COMMENT ON COLUMN good_doctors.created_on IS '입력일시';


-- goods_category definition

-- Drop table

-- DROP TABLE goods_category;

CREATE TABLE goods_category (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 분류id
	cls_nm varchar(50) NOT NULL, -- 분류명
	"level" int2 NOT NULL, -- 레벨
	parent_id int8 NULL, -- 상위분류id
	cls_cd varchar(20) NULL, -- 자체분류코드
	disp_ord varchar(10) NOT NULL, -- 표시순서
	supplier_id int8 NULL, -- 공급사id
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	CONSTRAINT pk_goods_category PRIMARY KEY (id),
	CONSTRAINT fk_goods_category_supplier_mst FOREIGN KEY (supplier_id) REFERENCES supplier_mst(id)
)
TABLESPACE ts_adm
;
CREATE INDEX ix_goods_category1 ON goods_category USING btree (supplier_id);
CREATE INDEX ix_goods_category2 ON goods_category USING btree (parent_id);
COMMENT ON TABLE goods_category IS '상품분류';

-- Column comments

COMMENT ON COLUMN goods_category.id IS '분류id';
COMMENT ON COLUMN goods_category.cls_nm IS '분류명';
COMMENT ON COLUMN goods_category."level" IS '레벨';
COMMENT ON COLUMN goods_category.parent_id IS '상위분류id';
COMMENT ON COLUMN goods_category.cls_cd IS '자체분류코드';
COMMENT ON COLUMN goods_category.disp_ord IS '표시순서';
COMMENT ON COLUMN goods_category.supplier_id IS '공급사id';
COMMENT ON COLUMN goods_category.created_by IS '입력자id';
COMMENT ON COLUMN goods_category.created_on IS '입력일시';
COMMENT ON COLUMN goods_category.updated_by IS '수정자id';
COMMENT ON COLUMN goods_category.updated_on IS '수정일시';


-- goods_mst definition

-- Drop table

-- DROP TABLE goods_mst;

CREATE TABLE goods_mst (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 상품id
	goods_type varchar(20) NOT NULL, -- 레몬상품종류
	cls_id int8 NOT NULL, -- 분류id
	goods_nm varchar(50) NOT NULL, -- 상품명
	goods_cd varchar(20) NULL, -- 자체상품코드
	disp_ord varchar(10) NOT NULL, -- 표시순서
	enabled bool NOT NULL DEFAULT true, -- 사용여부
	sale_enabled bool NOT NULL DEFAULT true, -- 판매여부
	sale_started_on timestamp NOT NULL, -- 판매시작일
	sale_ended_on timestamp NOT NULL, -- 판매종료일
	refund_enabled bool NOT NULL DEFAULT true, -- 환불허용여부
	cancel_enabled bool NOT NULL DEFAULT true, -- 취소허용여부
	consumer_price int4 NOT NULL, -- 소비자가격
	price int4 NOT NULL, -- 판매가격
	tax_enabled bool NOT NULL DEFAULT true, -- 과세여부
	tax_percent int4 NOT NULL, -- 과세율
	buy_amt int4 NULL, -- 매입가격
	buy_tax_enabled bool NOT NULL DEFAULT true, -- 매입과세여부
	buy_tax_percent int4 NULL, -- 매입과세율
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	CONSTRAINT pk_goods_mst PRIMARY KEY (id),
	CONSTRAINT fk_goods_mst_goods_category FOREIGN KEY (cls_id) REFERENCES goods_category(id)
)
TABLESPACE ts_adm
;
CREATE INDEX ix_goods_mst1 ON goods_mst USING btree (cls_id);
CREATE INDEX ix_goods_mst2 ON goods_mst USING btree (goods_nm);
CREATE INDEX ix_goods_mst3 ON goods_mst USING btree (goods_cd);
CREATE INDEX ix_goods_mst4 ON goods_mst USING btree (sale_started_on, sale_ended_on);
COMMENT ON TABLE goods_mst IS '상품마스타';

-- Column comments

COMMENT ON COLUMN goods_mst.id IS '상품id';
COMMENT ON COLUMN goods_mst.goods_type IS '레몬상품종류';
COMMENT ON COLUMN goods_mst.cls_id IS '분류id';
COMMENT ON COLUMN goods_mst.goods_nm IS '상품명';
COMMENT ON COLUMN goods_mst.goods_cd IS '자체상품코드';
COMMENT ON COLUMN goods_mst.disp_ord IS '표시순서';
COMMENT ON COLUMN goods_mst.enabled IS '사용여부';
COMMENT ON COLUMN goods_mst.sale_enabled IS '판매여부';
COMMENT ON COLUMN goods_mst.sale_started_on IS '판매시작일';
COMMENT ON COLUMN goods_mst.sale_ended_on IS '판매종료일';
COMMENT ON COLUMN goods_mst.refund_enabled IS '환불허용여부';
COMMENT ON COLUMN goods_mst.cancel_enabled IS '취소허용여부';
COMMENT ON COLUMN goods_mst.consumer_price IS '소비자가격';
COMMENT ON COLUMN goods_mst.price IS '판매가격';
COMMENT ON COLUMN goods_mst.tax_enabled IS '과세여부';
COMMENT ON COLUMN goods_mst.tax_percent IS '과세율';
COMMENT ON COLUMN goods_mst.buy_amt IS '매입가격';
COMMENT ON COLUMN goods_mst.buy_tax_enabled IS '매입과세여부';
COMMENT ON COLUMN goods_mst.buy_tax_percent IS '매입과세율';
COMMENT ON COLUMN goods_mst.created_by IS '입력자id';
COMMENT ON COLUMN goods_mst.created_on IS '입력일시';
COMMENT ON COLUMN goods_mst.updated_by IS '수정자id';
COMMENT ON COLUMN goods_mst.updated_on IS '수정일시';


-- goods_price_hst definition

-- Drop table

-- DROP TABLE goods_price_hst;

CREATE TABLE goods_price_hst (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 상품이력id
	goods_id int8 NOT NULL, -- 상품id
	started_on date NOT NULL, -- 유효시작일
	ended_on date NOT NULL, -- 유효종료일
	price int4 NOT NULL, -- 판매가격(V포함)
	buy_amt int4 NOT NULL, -- 매입가격(V포함)
	fee int4 NOT NULL, -- 대행수수료(V포함)
	CONSTRAINT pk_goods_price_hst PRIMARY KEY (id),
	CONSTRAINT uk_goods_price_hst UNIQUE (started_on, ended_on, goods_id),
	CONSTRAINT fk_goods_price_hst_goods_mst FOREIGN KEY (goods_id) REFERENCES goods_mst(id)
)
TABLESPACE ts_adm
;
COMMENT ON TABLE goods_price_hst IS '상품가격이력';

-- Column comments

COMMENT ON COLUMN goods_price_hst.id IS '상품이력id';
COMMENT ON COLUMN goods_price_hst.goods_id IS '상품id';
COMMENT ON COLUMN goods_price_hst.started_on IS '유효시작일';
COMMENT ON COLUMN goods_price_hst.ended_on IS '유효종료일';
COMMENT ON COLUMN goods_price_hst.price IS '판매가격(V포함)';
COMMENT ON COLUMN goods_price_hst.buy_amt IS '매입가격(V포함)';
COMMENT ON COLUMN goods_price_hst.fee IS '대행수수료(V포함)';


-- group_mbr definition

-- Drop table

-- DROP TABLE group_mbr;

CREATE TABLE group_mbr (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 그룹소속id
	group_id int8 NOT NULL, -- 그룹id
	hospital_id int8 NOT NULL, -- 병원id
	disp_ord varchar(10) NOT NULL, -- 표시순서
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	CONSTRAINT pk_group_mbr PRIMARY KEY (id),
	CONSTRAINT uk_group_mbr UNIQUE (hospital_id, group_id),
	CONSTRAINT fk_group_mbr_group_def FOREIGN KEY (group_id) REFERENCES group_def(id),
	CONSTRAINT fk_group_mbr_hospital_mst FOREIGN KEY (hospital_id) REFERENCES hospital_mst(id)
)
TABLESPACE ts_adm
;
COMMENT ON TABLE group_mbr IS '그룹소속병원';

-- Column comments

COMMENT ON COLUMN group_mbr.id IS '그룹소속id';
COMMENT ON COLUMN group_mbr.group_id IS '그룹id';
COMMENT ON COLUMN group_mbr.hospital_id IS '병원id';
COMMENT ON COLUMN group_mbr.disp_ord IS '표시순서';
COMMENT ON COLUMN group_mbr.created_by IS '입력자id';
COMMENT ON COLUMN group_mbr.created_on IS '입력일시';
COMMENT ON COLUMN group_mbr.updated_by IS '수정자id';
COMMENT ON COLUMN group_mbr.updated_on IS '수정일시';


-- hospital_attr definition

-- Drop table

-- DROP TABLE hospital_attr;

CREATE TABLE hospital_attr (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 부가정보id
	hospital_id int8 NOT NULL, -- 병원id
	attr_type varchar(20) NOT NULL, -- 속성구분
	attr_cd varchar(20) NOT NULL, -- 속성코드
	attr_nm varchar(50) NOT NULL, -- 속성명
	attr_cnt int4 NULL, -- 숫자값
	CONSTRAINT pk_hospital_attr PRIMARY KEY (id),
	CONSTRAINT fk_hospital_attr_hospital_mst FOREIGN KEY (hospital_id) REFERENCES hospital_mst(id)
)
TABLESPACE ts_adm
;
CREATE INDEX ix_hospital_attr1 ON hospital_attr USING btree (hospital_id, attr_type, attr_nm);
COMMENT ON TABLE hospital_attr IS '병원부가정보';

-- Column comments

COMMENT ON COLUMN hospital_attr.id IS '부가정보id';
COMMENT ON COLUMN hospital_attr.hospital_id IS '병원id';
COMMENT ON COLUMN hospital_attr.attr_type IS '속성구분';
COMMENT ON COLUMN hospital_attr.attr_cd IS '속성코드';
COMMENT ON COLUMN hospital_attr.attr_nm IS '속성명';
COMMENT ON COLUMN hospital_attr.attr_cnt IS '숫자값';


-- hospital_bed definition

-- Drop table

-- DROP TABLE hospital_bed;

CREATE TABLE hospital_bed (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 시설id
	hospital_id int8 NOT NULL, -- 병원id
	bed_cd varchar(20) NOT NULL, -- 병상종류코드
	bed_nm varchar(30) NOT NULL, -- 병상종류명
	bed_cnt int4 NOT NULL, -- 병상수
	CONSTRAINT pk_hospital_bed PRIMARY KEY (id),
	CONSTRAINT fk_hospital_bed_hospital_mst FOREIGN KEY (hospital_id) REFERENCES hospital_mst(id)
)
TABLESPACE ts_adm
;
CREATE INDEX ix_hospital_bed1 ON hospital_bed USING btree (hospital_id, bed_cd);
COMMENT ON TABLE hospital_bed IS '병원병실정보';

-- Column comments

COMMENT ON COLUMN hospital_bed.id IS '시설id';
COMMENT ON COLUMN hospital_bed.hospital_id IS '병원id';
COMMENT ON COLUMN hospital_bed.bed_cd IS '병상종류코드';
COMMENT ON COLUMN hospital_bed.bed_nm IS '병상종류명';
COMMENT ON COLUMN hospital_bed.bed_cnt IS '병상수';


-- hospital_directions definition

-- Drop table

-- DROP TABLE hospital_directions;

CREATE TABLE hospital_directions (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 교통정보id
	hospital_id int8 NOT NULL, -- 병원id
	transport_nm varchar(256) NOT NULL, -- 교통편
	transport_line varchar(256) NULL, -- 노선번호
	alight_txt varchar(256) NULL, -- 하차지점
	way_txt varchar(500) NULL, -- 방향
	distance_txt varchar(256) NULL, -- 거리
	remark_txt varchar(500) NULL, -- 비고
	updated_on timestamp NULL, -- 수정일자
	CONSTRAINT pk_hospital_directions PRIMARY KEY (id),
	CONSTRAINT fk_hospital_directions_hospital_mst FOREIGN KEY (hospital_id) REFERENCES hospital_mst(id)
)
TABLESPACE ts_adm
;
CREATE INDEX ix_hospital_directions1 ON hospital_directions USING btree (hospital_id);
COMMENT ON TABLE hospital_directions IS '교통정보';

-- Column comments

COMMENT ON COLUMN hospital_directions.id IS '교통정보id';
COMMENT ON COLUMN hospital_directions.hospital_id IS '병원id';
COMMENT ON COLUMN hospital_directions.transport_nm IS '교통편';
COMMENT ON COLUMN hospital_directions.transport_line IS '노선번호';
COMMENT ON COLUMN hospital_directions.alight_txt IS '하차지점';
COMMENT ON COLUMN hospital_directions.way_txt IS '방향';
COMMENT ON COLUMN hospital_directions.distance_txt IS '거리';
COMMENT ON COLUMN hospital_directions.remark_txt IS '비고';
COMMENT ON COLUMN hospital_directions.updated_on IS '수정일자';


-- hospital_file definition

-- Drop table

-- DROP TABLE hospital_file;

CREATE TABLE hospital_file (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 파일id
	hospital_id int8 NOT NULL, -- 병원id
	file_nm varchar(100) NOT NULL, -- 파일이름
	file_uri varchar(256) NOT NULL, -- 파일uri
	disp_ord varchar(10) NOT NULL, -- 표시순서
	hash_tag varchar(256) NULL, -- 이미지태그
	thumb_url varchar(256) NULL, -- 썸네일url
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	CONSTRAINT pk_hospital_file PRIMARY KEY (id),
	CONSTRAINT fk_hospital_file_hospital_mst FOREIGN KEY (hospital_id) REFERENCES hospital_mst(id)
)
TABLESPACE ts_adm
;
CREATE INDEX ix_hospital_file1 ON hospital_file USING btree (hospital_id);
COMMENT ON TABLE hospital_file IS '병원사진';

-- Column comments

COMMENT ON COLUMN hospital_file.id IS '파일id';
COMMENT ON COLUMN hospital_file.hospital_id IS '병원id';
COMMENT ON COLUMN hospital_file.file_nm IS '파일이름';
COMMENT ON COLUMN hospital_file.file_uri IS '파일uri';
COMMENT ON COLUMN hospital_file.disp_ord IS '표시순서';
COMMENT ON COLUMN hospital_file.hash_tag IS '이미지태그';
COMMENT ON COLUMN hospital_file.thumb_url IS '썸네일url';
COMMENT ON COLUMN hospital_file.created_by IS '입력자id';
COMMENT ON COLUMN hospital_file.created_on IS '입력일시';


-- hospital_service definition

-- Drop table

-- DROP TABLE hospital_service;

CREATE TABLE hospital_service (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 서비스id
	hospital_id int8 NOT NULL, -- 병원id
	service_cd varchar(20) NOT NULL, -- 서비스코드
	enabled bool NOT NULL, -- 사용여부
	start_date date NOT NULL, -- 시작일
	end_date date NOT NULL, -- 종료일
	CONSTRAINT pk_hospital_service PRIMARY KEY (id),
	CONSTRAINT uk_hospital_service UNIQUE (hospital_id, service_cd),
	CONSTRAINT fk_hospital_service_hospital_mst FOREIGN KEY (hospital_id) REFERENCES hospital_mst(id)
)
TABLESPACE ts_adm
;
COMMENT ON TABLE hospital_service IS '병원레몬서비스';

-- Column comments

COMMENT ON COLUMN hospital_service.id IS '서비스id';
COMMENT ON COLUMN hospital_service.hospital_id IS '병원id';
COMMENT ON COLUMN hospital_service.service_cd IS '서비스코드';
COMMENT ON COLUMN hospital_service.enabled IS '사용여부';
COMMENT ON COLUMN hospital_service.start_date IS '시작일';
COMMENT ON COLUMN hospital_service.end_date IS '종료일';


-- hospital_treat definition

-- Drop table

-- DROP TABLE hospital_treat;

CREATE TABLE hospital_treat (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 진료과목id
	hospital_id int8 NOT NULL, -- 병원id
	treat_cd varchar(2) NOT NULL, -- 진료과목코드
	treat_nm varchar(50) NOT NULL, -- 진료과목명
	sdoctor_cnt int4 NOT NULL, -- 전문의수
	odoctor_cnt int4 NOT NULL, -- 선택진료의사수
	CONSTRAINT pk_hospital_treat PRIMARY KEY (id),
	CONSTRAINT fk_hospital_treat_hospital_mst FOREIGN KEY (hospital_id) REFERENCES hospital_mst(id)
)
TABLESPACE ts_adm
;
CREATE INDEX ix_hospital_treat1 ON hospital_treat USING btree (hospital_id, treat_nm);
COMMENT ON TABLE hospital_treat IS '병원진료과목';

-- Column comments

COMMENT ON COLUMN hospital_treat.id IS '진료과목id';
COMMENT ON COLUMN hospital_treat.hospital_id IS '병원id';
COMMENT ON COLUMN hospital_treat.treat_cd IS '진료과목코드';
COMMENT ON COLUMN hospital_treat.treat_nm IS '진료과목명';
COMMENT ON COLUMN hospital_treat.sdoctor_cnt IS '전문의수';
COMMENT ON COLUMN hospital_treat.odoctor_cnt IS '선택진료의사수';


-- menu_service definition

-- Drop table

-- DROP TABLE menu_service;

CREATE TABLE menu_service (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 서비스메뉴id
	menu_id int8 NOT NULL, -- 메뉴id
	menu_ord varchar(256) NOT NULL, -- 표시순서
	enabled bool NOT NULL DEFAULT true, -- 사용여부
	"level" int4 NOT NULL, -- 레벨
	ovrd_menu_nm varchar(100) NULL, -- 재정의메뉴명
	ovrd_menu_nls varchar(100) NULL, -- 재정의메뉴다국어
	ovrd_service_url varchar(256) NULL, -- 재정의서비스url
	ovrd_img_url varchar(256) NULL, -- 재정의이미지url
	up_id int8 NULL, -- 상위메뉴id
	hospital_id int8 NULL, -- 병원id
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	CONSTRAINT pk_menu_service PRIMARY KEY (id),
	CONSTRAINT fk_menu_service_menu_def FOREIGN KEY (menu_id) REFERENCES menu_def(id),
	CONSTRAINT fk_menu_service_self FOREIGN KEY (up_id) REFERENCES menu_service(id)
)
TABLESPACE ts_adm
;
CREATE INDEX ix_menu_service1 ON menu_service USING btree (hospital_id);
CREATE INDEX ix_menu_service2 ON menu_service USING btree (menu_id);
CREATE INDEX ix_menu_service3 ON menu_service USING btree (up_id);
COMMENT ON TABLE menu_service IS '서비스메뉴';

-- Column comments

COMMENT ON COLUMN menu_service.id IS '서비스메뉴id';
COMMENT ON COLUMN menu_service.menu_id IS '메뉴id';
COMMENT ON COLUMN menu_service.menu_ord IS '표시순서';
COMMENT ON COLUMN menu_service.enabled IS '사용여부';
COMMENT ON COLUMN menu_service."level" IS '레벨';
COMMENT ON COLUMN menu_service.ovrd_menu_nm IS '재정의메뉴명';
COMMENT ON COLUMN menu_service.ovrd_menu_nls IS '재정의메뉴다국어';
COMMENT ON COLUMN menu_service.ovrd_service_url IS '재정의서비스url';
COMMENT ON COLUMN menu_service.ovrd_img_url IS '재정의이미지url';
COMMENT ON COLUMN menu_service.up_id IS '상위메뉴id';
COMMENT ON COLUMN menu_service.hospital_id IS '병원id';
COMMENT ON COLUMN menu_service.created_by IS '입력자id';
COMMENT ON COLUMN menu_service.created_on IS '입력일시';
COMMENT ON COLUMN menu_service.updated_by IS '수정자id';
COMMENT ON COLUMN menu_service.updated_on IS '수정일시';


-- post definition

-- Drop table

-- DROP TABLE post;

CREATE TABLE post (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 게시물id
	board_id int8 NOT NULL, -- 게시판id
	post_title varchar(100) NOT NULL, -- 제목
	post_content text NOT NULL, -- 게시내용
	post_enabled bool NOT NULL DEFAULT false, -- 게시여부
	started_on timestamp NOT NULL, -- 게시시작일시
	ended_on timestamp NOT NULL DEFAULT '2099-12-31 00:00:00'::timestamp without time zone, -- 게시종료일시
	board_type varchar(20) NOT NULL, -- 게시판종류
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	reply_enabled bool NULL, -- 답변완료여부
	hospital_id int8 NULL, -- 병원id
	hospital_nm varchar(30) NULL, -- 이용병원명
	treat_dept_cd varchar(20) NULL, -- 진료과코드
	treat_dept_nm varchar(50) NULL, -- 진료과명
	doctor_cd varchar(20) NULL, -- 의사코드
	doctor_nm varchar(30) NULL, -- 의사명
	score int4 NULL, -- 평가점수
	visit_date date NULL, -- 이용일자
	like_cnt int4 NULL, -- 추천수
	req_hospital_nm varchar(20) NULL, -- 문의병원명
	guest_nm varchar(20) NULL, -- 문의자성명
	email varchar(50) NULL, -- 이메일
	cell_phone_no varchar(30) NULL, -- 연락처
	faq_cls varchar(20) NULL, -- FAQ분류
	disp_ord varchar(10) NULL, -- FAQ표시순서
	CONSTRAINT pk_post PRIMARY KEY (id),
	CONSTRAINT fk_post_board FOREIGN KEY (board_id) REFERENCES board(id)
)
TABLESPACE ts_adm
;
CREATE INDEX ix_post1 ON post USING btree (board_id);
CREATE INDEX ix_post2 ON post USING btree (started_on, ended_on, post_enabled);
CREATE INDEX ix_post3 ON post USING btree (post_title);
CREATE INDEX ix_post4 ON post USING btree (created_by);
CREATE INDEX ix_post5 ON post USING btree (created_on DESC);
CREATE INDEX ix_post6 ON post USING btree (post_content);
COMMENT ON TABLE post IS '게시물';

-- Column comments

COMMENT ON COLUMN post.id IS '게시물id';
COMMENT ON COLUMN post.board_id IS '게시판id';
COMMENT ON COLUMN post.post_title IS '제목';
COMMENT ON COLUMN post.post_content IS '게시내용';
COMMENT ON COLUMN post.post_enabled IS '게시여부';
COMMENT ON COLUMN post.started_on IS '게시시작일시';
COMMENT ON COLUMN post.ended_on IS '게시종료일시';
COMMENT ON COLUMN post.board_type IS '게시판종류';
COMMENT ON COLUMN post.created_by IS '입력자id';
COMMENT ON COLUMN post.created_on IS '입력일시';
COMMENT ON COLUMN post.updated_by IS '수정자id';
COMMENT ON COLUMN post.updated_on IS '수정일시';
COMMENT ON COLUMN post.reply_enabled IS '답변완료여부';
COMMENT ON COLUMN post.hospital_id IS '병원id';
COMMENT ON COLUMN post.hospital_nm IS '이용병원명';
COMMENT ON COLUMN post.treat_dept_cd IS '진료과코드';
COMMENT ON COLUMN post.treat_dept_nm IS '진료과명';
COMMENT ON COLUMN post.doctor_cd IS '의사코드';
COMMENT ON COLUMN post.doctor_nm IS '의사명';
COMMENT ON COLUMN post.score IS '평가점수';
COMMENT ON COLUMN post.visit_date IS '이용일자';
COMMENT ON COLUMN post.like_cnt IS '추천수';
COMMENT ON COLUMN post.req_hospital_nm IS '문의병원명';
COMMENT ON COLUMN post.guest_nm IS '문의자성명';
COMMENT ON COLUMN post.email IS '이메일';
COMMENT ON COLUMN post.cell_phone_no IS '연락처';
COMMENT ON COLUMN post.faq_cls IS 'FAQ분류';
COMMENT ON COLUMN post.disp_ord IS 'FAQ표시순서';


-- post_file definition

-- Drop table

-- DROP TABLE post_file;

CREATE TABLE post_file (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 파일id
	post_id int8 NOT NULL, -- 게시물id
	file_nm varchar(100) NOT NULL, -- 파일이름
	file_uri varchar(256) NOT NULL, -- 파일uri
	file_size int4 NOT NULL, -- 파일크기
	file_type varchar(20) NOT NULL, -- 파일유형
	thumb_url varchar(256) NULL, -- 썸네일url
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	CONSTRAINT pk_post_file PRIMARY KEY (id),
	CONSTRAINT fk_post_file_post FOREIGN KEY (post_id) REFERENCES post(id)
)
TABLESPACE ts_adm
;
CREATE INDEX ix_post_file1 ON post_file USING btree (post_id);
COMMENT ON TABLE post_file IS '게시물첨부파일';

-- Column comments

COMMENT ON COLUMN post_file.id IS '파일id';
COMMENT ON COLUMN post_file.post_id IS '게시물id';
COMMENT ON COLUMN post_file.file_nm IS '파일이름';
COMMENT ON COLUMN post_file.file_uri IS '파일uri';
COMMENT ON COLUMN post_file.file_size IS '파일크기';
COMMENT ON COLUMN post_file.file_type IS '파일유형';
COMMENT ON COLUMN post_file.thumb_url IS '썸네일url';
COMMENT ON COLUMN post_file.created_by IS '입력자id';
COMMENT ON COLUMN post_file.created_on IS '입력일시';


-- post_reply definition

-- Drop table

-- DROP TABLE post_reply;

CREATE TABLE post_reply (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 답변id
	reply_title varchar(100) NOT NULL, -- 제목
	reply_content text NOT NULL, -- 답변내용
	post_id int8 NOT NULL, -- 게시물id
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	CONSTRAINT pk_post_reply PRIMARY KEY (id),
	CONSTRAINT fk_post_reply_post FOREIGN KEY (post_id) REFERENCES post(id)
)
TABLESPACE ts_adm
;
CREATE INDEX ix_post_reply1 ON post_reply USING btree (post_id);
CREATE INDEX ix_post_reply2 ON post_reply USING btree (reply_title);
COMMENT ON TABLE post_reply IS '게시물답변';

-- Column comments

COMMENT ON COLUMN post_reply.id IS '답변id';
COMMENT ON COLUMN post_reply.reply_title IS '제목';
COMMENT ON COLUMN post_reply.reply_content IS '답변내용';
COMMENT ON COLUMN post_reply.post_id IS '게시물id';
COMMENT ON COLUMN post_reply.created_by IS '입력자id';
COMMENT ON COLUMN post_reply.created_on IS '입력일시';
COMMENT ON COLUMN post_reply.updated_by IS '수정자id';
COMMENT ON COLUMN post_reply.updated_on IS '수정일시';


-- role_menu definition

-- Drop table

-- DROP TABLE role_menu;

CREATE TABLE role_menu (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 역할메뉴id
	menu_service_id int8 NOT NULL, -- 메뉴id
	role_id int8 NOT NULL, -- 역할id
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	CONSTRAINT pk_role_menu PRIMARY KEY (id),
	CONSTRAINT uk_role_menu UNIQUE (menu_service_id, role_id),
	CONSTRAINT fk_role_menu_menu_service FOREIGN KEY (menu_service_id) REFERENCES menu_service(id),
	CONSTRAINT fk_role_menu_role_def FOREIGN KEY (role_id) REFERENCES role_def(id)
)
TABLESPACE ts_adm
;
COMMENT ON TABLE role_menu IS '역할별메뉴설정';

-- Column comments

COMMENT ON COLUMN role_menu.id IS '역할메뉴id';
COMMENT ON COLUMN role_menu.menu_service_id IS '메뉴id';
COMMENT ON COLUMN role_menu.role_id IS '역할id';
COMMENT ON COLUMN role_menu.created_by IS '입력자id';
COMMENT ON COLUMN role_menu.created_on IS '입력일시';
COMMENT ON COLUMN role_menu.updated_by IS '수정자id';
COMMENT ON COLUMN role_menu.updated_on IS '수정일시';


-- role_privilege definition

-- Drop table

-- DROP TABLE role_privilege;

CREATE TABLE role_privilege (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 역할권한id
	role_id int8 NOT NULL, -- 역할id
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	CONSTRAINT pk_role_privilege PRIMARY KEY (id),
	CONSTRAINT uk_role_privilege UNIQUE (role_id),
	CONSTRAINT fk_role_privilege_role_def FOREIGN KEY (role_id) REFERENCES role_def(id)
)
TABLESPACE ts_adm
;
COMMENT ON TABLE role_privilege IS '역할별권한지정';

-- Column comments

COMMENT ON COLUMN role_privilege.id IS '역할권한id';
COMMENT ON COLUMN role_privilege.role_id IS '역할id';
COMMENT ON COLUMN role_privilege.created_by IS '입력자id';
COMMENT ON COLUMN role_privilege.created_on IS '입력일시';
COMMENT ON COLUMN role_privilege.updated_by IS '수정자id';
COMMENT ON COLUMN role_privilege.updated_on IS '수정일시';


-- menu_content definition

-- Drop table

-- DROP TABLE menu_content;

CREATE TABLE menu_content (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 컨텐트id
	menu_service_id int8 NOT NULL, -- 서비스메뉴id
	nls_cd varchar(20) NOT NULL, -- 언어코드
	html_content text NOT NULL, -- 컨텐트내용
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	CONSTRAINT pk_menu_content PRIMARY KEY (id),
	CONSTRAINT uk_menu_content UNIQUE (menu_service_id, nls_cd),
	CONSTRAINT fk_menu_content_menu_service FOREIGN KEY (menu_service_id) REFERENCES menu_service(id)
)
TABLESPACE ts_adm
;
COMMENT ON TABLE menu_content IS '정적컨텐트';

-- Column comments

COMMENT ON COLUMN menu_content.id IS '컨텐트id';
COMMENT ON COLUMN menu_content.menu_service_id IS '서비스메뉴id';
COMMENT ON COLUMN menu_content.nls_cd IS '언어코드';
COMMENT ON COLUMN menu_content.html_content IS '컨텐트내용';
COMMENT ON COLUMN menu_content.created_by IS '입력자id';
COMMENT ON COLUMN menu_content.created_on IS '입력일시';
COMMENT ON COLUMN menu_content.updated_by IS '수정자id';
COMMENT ON COLUMN menu_content.updated_on IS '수정일시';


-- menu_cstm definition

-- Drop table

-- DROP TABLE menu_cstm;

CREATE TABLE menu_cstm (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 맞춤설정id
	menu_service_id int8 NOT NULL, -- 서비스메뉴id
	attr_key varchar(30) NOT NULL, -- 속성키
	attr_val varchar(200) NOT NULL, -- 속성값
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	CONSTRAINT pk_menu_cstm PRIMARY KEY (id),
	CONSTRAINT uk_menu_cstm UNIQUE (menu_service_id, attr_key),
	CONSTRAINT fk_menu_cstm_menu_service FOREIGN KEY (menu_service_id) REFERENCES menu_service(id)
)
TABLESPACE ts_adm
;
COMMENT ON TABLE menu_cstm IS '메뉴맞춤설정';

-- Column comments

COMMENT ON COLUMN menu_cstm.id IS '맞춤설정id';
COMMENT ON COLUMN menu_cstm.menu_service_id IS '서비스메뉴id';
COMMENT ON COLUMN menu_cstm.attr_key IS '속성키';
COMMENT ON COLUMN menu_cstm.attr_val IS '속성값';
COMMENT ON COLUMN menu_cstm.created_by IS '입력자id';
COMMENT ON COLUMN menu_cstm.created_on IS '입력일시';
COMMENT ON COLUMN menu_cstm.updated_by IS '수정자id';
COMMENT ON COLUMN menu_cstm.updated_on IS '수정일시';


-- user_n definition

-- Drop table

-- DROP TABLE user_n;

CREATE TABLE user_n (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 관리자id
	user_id int8 NOT NULL, -- 사용자id
	hospital_id int8 NOT NULL, -- 병원id
	n_status varchar(20) NOT NULL, -- 관리자상태
	n_level int4 NOT NULL, -- 관리자레벨
	applied_on timestamp NOT NULL, -- 신청일시
	approved_on timestamp NULL, -- 승인일시
	CONSTRAINT pk_user_n PRIMARY KEY (id),
	CONSTRAINT uk_user_n UNIQUE (user_id, hospital_id)
)
TABLESPACE ts_adm
;
COMMENT ON TABLE user_n IS '관리자정보';

-- Column comments

COMMENT ON COLUMN user_n.id IS '관리자id';
COMMENT ON COLUMN user_n.user_id IS '사용자id';
COMMENT ON COLUMN user_n.hospital_id IS '병원id';
COMMENT ON COLUMN user_n.n_status IS '관리자상태';
COMMENT ON COLUMN user_n.n_level IS '관리자레벨';
COMMENT ON COLUMN user_n.applied_on IS '신청일시';
COMMENT ON COLUMN user_n.approved_on IS '승인일시';


-- user_role definition

-- Drop table

-- DROP TABLE user_role;

CREATE TABLE user_role (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- 역할배정id
	user_id int8 NOT NULL, -- 사용자id
	role_id int8 NOT NULL, -- 역할id
	created_by int8 NOT NULL, -- 입력자id
	created_on timestamp NOT NULL, -- 입력일시
	updated_by int8 NULL, -- 수정자id
	updated_on timestamp NULL, -- 수정일시
	CONSTRAINT pk_user_role PRIMARY KEY (id),
	CONSTRAINT uk_user_role UNIQUE (user_id, role_id)
)
TABLESPACE ts_adm
;
COMMENT ON TABLE user_role IS '사용자역할배정';

-- Column comments

COMMENT ON COLUMN user_role.id IS '역할배정id';
COMMENT ON COLUMN user_role.user_id IS '사용자id';
COMMENT ON COLUMN user_role.role_id IS '역할id';
COMMENT ON COLUMN user_role.created_by IS '입력자id';
COMMENT ON COLUMN user_role.created_on IS '입력일시';
COMMENT ON COLUMN user_role.updated_by IS '수정자id';
COMMENT ON COLUMN user_role.updated_on IS '수정일시';


-- user_n foreign keys

ALTER TABLE user_n ADD CONSTRAINT fk_user_n_hospital_mst FOREIGN KEY (hospital_id) REFERENCES hospital_mst(id);
ALTER TABLE user_n ADD CONSTRAINT fk_user_n_user_mst FOREIGN KEY (user_id) REFERENCES mbr.user_mst(id);


-- user_role foreign keys

ALTER TABLE user_role ADD CONSTRAINT fk_user_role_role_def FOREIGN KEY (role_id) REFERENCES role_def(id);
ALTER TABLE user_role ADD CONSTRAINT fk_user_role_user_mst FOREIGN KEY (user_id) REFERENCES mbr.user_mst(id);
